config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/accounts'
    get 'admin/users'
    get 'admin/show_account/:id', to: "admin#show_account", as: "admin_account"
    get 'admin/show_user/:id', to: "admin#show_user", as: "admin_user"
  end
  
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord

    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :user
  end
  
  has_many :accounts, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user = current_user
    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:balance)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def accounts
    @accnts = Account.all
  end

  def users
    @users = User.all
  end

  def show_account
    @accnt = Account.find(params[:id])
  end
  def show_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <p>This account belongs to <%= account.user.email %> </p>
    Account #
    <%= account.id %>
    <strong>. Balance:</strong>
    <%= account.balance %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.number_field :balance %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<div class="container m-5">
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>
<br>
<div id="accounts">
  <% @accounts.each do |account| %>
      <% if account.user == current_user %>
      <%= render account %>
      <p>
        <%= link_to "Show this account", account %>
      </p>
      <% end %>
    <% end %>
</div>

<%= link_to "New account", new_account_path %>

<%= link_to "Home Page", root_path %>

</div>

app/views/accounts/new.html.erb
<div class="container m-5">
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>
</div>

app/views/accounts/show.html.erb
<div class="container m-5">
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <p>  </p>
  <%= button_to "Destroy this account", @account, method: :delete %>
</div>
</div>

app/views/admin/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <%= link_to "Dashboard", admin_path, class: "nav-link" %>
  <%= link_to "Accounts", admin_accounts_path, class: "nav-link" %>
  <%= link_to "Users", admin_users_path, class: "nav-link" %>
  <%= link_to "Home", root_path, class: "nav-link" %>
</div>

app/views/admin/accounts.html.erb
<%= render "admin/navbar" %>
<h1>Admin#accounts</h1>
<p>Find me in app/views/admin/accounts.html.erb</p>

<div class = "container m-5" >
    <table class="table table-striped table-hover">
    <thead>
        <tr> 
            <th scope = "col" > Id </th>
            <th scope = "col" > User </th>
            <th scope = "col" > Balance </th>
            <th scope = "col" > Details </th>
        </tr>
    </thead>
    <tbody>
        <% @accnts.each do |accnt| %>
            <tr>
                <th scope="row" > <%= accnt.id %> </th>
                <td> <%= accnt.user.email %> </td>
                <td>  <%= accnt.balance %> </td>
                <td> <%= link_to "More Info", admin_account_path(accnt) %> </td>
            </tr>
        <%end%>
    </tbody>
    </table>
</div>

app/views/admin/index.html.erb
<%= render "admin/navbar" %>
<%= stylesheet_link_tag "/assets/stylesheets/admin_index.css" %> 
<div class="container" >
    <h1 class="text-center mt-5" > Admin Page </h1> 

    <div class = "box"> 
        <ul class = 'list-group' >
        <li class = 'list-group-item' > <%= link_to "Accounts", admin_accounts_path %></li>
        <li class = 'list-group-item' > <%= link_to "Users", admin_users_path %></li>

        </ul>  
    </div>    
</div>

app/views/admin/show_account.html.erb
<%= render "admin/navbar" %>
<div class = "container m-5" >
<h1>Admin#show_account</h1>
<p>Find me in app/views/admin/show_account.html.erb</p>

<p class="lead">
  This account belongs to <%= @accnt.user.email %>
</p>

<p>
    Current Information:-
    <ul class = 'list-group' >
        <li class = 'list-group-item' > Balance : <%= @accnt.balance %></li>
        <li class = 'list-group-item' > Created at : <%= @accnt.created_at %></li>
        <li class = 'list-group-item' > Updated at : <%= @accnt.updated_at %></li>
    </ul>  
</p>

<h2> Actions:- <h2>

  <%= link_to "Edit", edit_account_path(@accnt), class:"btn btn-info" %>
  
  <%= button_to "Delete", @accnt, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %>

</div>

app/views/admin/show_user.html.erb
<%= render "admin/navbar" %>
<div class = "container m-5" >
<p class="lead">
  This account belongs to <%= @user.email %>
</p>

<p>
    Current Information:-
    <ul class = 'list-group' >
        <li class = 'list-group-item' > Accounts : <%= @user.accounts.size %></li>
        <li class = 'list-group-item' > Created at : <%= @user.created_at %></li>
        <li class = 'list-group-item' > Updated at : <%= @user.updated_at %></li>
    </ul>  
</p>
</div>

app/views/admin/users.html.erb
<%= render "admin/navbar" %>
<h1>Admin#users</h1>
<p>Find me in app/views/admin/users.html.erb</p>

<div class = "container m-5" >
    <table class="table table-striped table-hover">
    <thead>
        <tr> 
            <th scope = "col" > Id  </th>
            <th scope = "col" > Email </th>
            <th scope = "col" > Status </th>
            <th scope = "col" > Accounts </th>
            <th scope = "col" > Details </th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <th scope="row" > <%= user.id %> </th>
                <td> <%= user.email %> </td>
                <td> <%= user.role %> </td>     
                <td>  <%= user.accounts.size %> </td>
                <td> <%= link_to "More Info", admin_user_path(user) %> </td>
            </tr>
        <%end%>
    </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "container m-5">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>

  <% if current_user %>
    <h2> Hello <%= current_user.email %> </h2>

    <div class="alert alert-success" role="alert">
      <p>You have logged in succesfully. </p>
    </div>
    <p>You are <%= current_user.role %> </p>
    
    <% if current_user.admin? %>
        <p>There are <%= User.count%> users in the system.</p>
        <%= link_to "Admin Dashboard", admin_path %>
    <% else %>
    <%= link_to "Accounts", accounts_path %> 
    <% end %>
    
    <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete  %>
    
    <% else %>
    <div class="alert alert-danger" role="alert">
      <p>You are not logged in.</p>
    </div>
    
    <%= link_to "Sign Up", new_user_registration_path %>
    <%= link_to "Log in", new_user_session_path %>
    
  <% end %>
</div>